services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: server
    ports:
      - "3001:3001"
    environment:
      TOKEN_KEY: "verykooltoken"
      DB_CONNECTION_STRING: "mongodb://database:27017/test"
      PORT: 3001
  database:
    image: mongo
    volumes:
      - database_data:/data/db
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        REACT_APP_SERVER: "http://localhost:3001"
    image: client
    ports:
      - "3000:3000"

volumes:
  database_data: { }
